" Enable syntax highlighting
syntax on

" Highlight trailing whitespace with red
:highlight ExtraWhitespace ctermbg=red guibg=red
:match ExtraWhitespace /\s\+$/

" Execute pathogen
execute pathogen#infect()
execute pathogen#helptags()

" Enable indention character
let g:indentLine_color_term = 239
let g:indentLine_color_gui = '#09AA08'
let g:indentLine_char = '│'

augroup filetypedetect
" Filetype: pig
au BufNewFile,BufRead *.pig setf pig
" Filetype: avsc
au BufNewFile,BufRead *.avsc setf avro-idl
" Filetype: py
au BufNewFile,BufRead *.py setf python
augroup END

" Tab to 4 spaces
set tabstop=4
set shiftwidth=4
set expandtab
